version: '3'

services:
  frontend:
    image: node:21.4.0
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    entrypoint: /app/entrypoint.sh
    command: npm run dev

  backend:
    image: node:21.4.0
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: npm run start

  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

